### ISSUE TITLE
Merge with slim

### ISSUE THREAD

**Issue by cdprincipe** [dannyn/slimlock#4]
Is possible merge this with
http://git.berlios.de/cgi-bin/gitweb.cgi?p=slim

**Comment by cdprincipe** [comment]
from 21 Mar 2013 slimlock is mantained also in slim
http://git.berlios.de/cgi-bin/gitweb.cgi?p=slim;a=commit;h=fccae89bbf97eb77b3c7a6c55b37ffa9c60eeaee

**Comment by dannyn** [comment]
This is already being worked on.

**Comment by cdprincipe** [comment]
Great!
